language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo add-apt-repository ppa:ubuntu-lxc/daily -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq coccinelle parallel libapparmor-dev libcap-dev libseccomp-dev python3-dev python3-setuptools docbook2x libgnutls-dev libselinux1-dev linux-libc-dev
script:
 - ./coccinelle/run-coccinelle.sh -i
 - git diff --exit-code
 - ./autogen.sh
 - rm -Rf build
 - mkdir build
 - cd build
 - ../configure --enable-tests --with-distro=unknown
 - make -j4
 - make DESTDIR=$TRAVIS_BUILD_DIR/install install
 - cd ../config/apparmor
 - ./lxc-generate-aa-rules.py container-rules.base > /tmp/output
 - diff /tmp/output container-rules

notifications:
  email:
    recipients:
      - lxc-devel@lists.linuxcontainers.org
  webhooks: https://linuxcontainers.org/webhook-lxcbot/
