language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo add-apt-repository ppa:ubuntu-lxc/daily -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq coccinelle parallel libapparmor-dev libcap-dev libseccomp-dev python3-dev python3-setuptools docbook2x libselinux1-dev linux-libc-dev
script: src/tests/travis.sh
notifications:
  email:
    recipients:
      - lxc-devel@lists.linuxcontainers.org
  webhooks: https://linuxcontainers.org/webhook-lxcbot/
