name: Sanitizers build
on:
  - push
  - pull_request
jobs:
  sanitizers:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc
          - clang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compiler version
        env:
          CC: ${{ matrix.compiler }}
        run: |
          ${CC} --version

      - name: Kernel version
        run: |
          uname -a

      - name: Mount table
        run: |
          findmnt

      - name: Hardening options
        run: |
          sudo cat /proc/sys/fs/protected_fifos
          sudo cat /proc/sys/fs/protected_hardlinks
          sudo cat /proc/sys/fs/protected_symlinks
          sudo cat /proc/sys/fs/protected_regular

      - name: Build
        run: |
          echo 1 | sudo tee -a /proc/sys/fs/protected_regular || true
          sudo chmod -R 755 /home
          sudo CC=${{ matrix.compiler }} CXX=${{ matrix.compiler }}++ .github/workflows/sanitizers.sh
